[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.zksync]
src = 'contracts'
libs = ['lib']
solc-version = "0.8.24"
fallback_oz = true
is_system = false
mode = "3"
